name: codespell

on: [push]

jobs:
  codespell:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install prerequisites
      run: sudo pip install codespell
    - name: check
      run: codespell -c -q 2 --skip="yarn.lock"
